version: "3"
services: 
  app:
    container_name: gs_backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    env_file: 
      - ./.env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - "/home/db/mongo:/data/db"
networks: 
  default:
    external:
      name: gsnet