version: "3"
services: 
  gsback:
    container_name: gsback
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    env_file: 
      - ./.env
    volumes:
      - "/home/ssc/gsData:/home/node/app/data"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - "/home/ssc/mongo:/data/db"
networks: 
  default:
    external:
      name: gsnet