version: "3"
services: 
  app:
    container_name: gs_backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    links:
      - mongo
    env_file: 
      - ./.env
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes: 
      - "/home/db/mongo:/data/db"